# Generated by Django 5.1.3 on 2025-01-06 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категория')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quizz.category', verbose_name='Родитель категории')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': '2. Подкатегория',
                'verbose_name_plural': '2. Подкатегория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quizz.category',),
        ),
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
            ],
            options={
                'verbose_name': '1. Основная категория',
                'verbose_name_plural': '1. Основная категория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quizz.category',),
        ),
    ]
