# Generated by Django 5.1.3 on 2025-01-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quiz_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': '3. Тест', 'verbose_name_plural': '3. Тести'},
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст вопроса'),
        ),
    ]
