# Generated by Django 5.1.4 on 2025-01-08 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_alter_quiz_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.AddField(
            model_name='quiz',
            name='degree',
            field=models.CharField(blank=True, choices=[('1', 'Магистр'), ('2', 'Бакалавр')], max_length=10, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('1', 'Очное'), ('2', 'Вечернее'), ('3', 'Дистанционное'), ('4', 'Экстернат')], max_length=10, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II')], max_length=2, null=True, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI')], max_length=2, null=True, verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста'),
        ),
        migrations.CreateModel(
            name='OrderQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_order', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_quiz', to='quizz.quiz', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': '3. Тест',
                'verbose_name_plural': '3. Тести',
            },
        ),
    ]
