# Generated by Django 5.1.4 on 2025-01-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_remove_quiz_description_quiz_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='degree',
        ),
    ]
