# Generated by Django 5.1.4 on 2025-01-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_quizquestion_questionoption_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='fields',
            new_name='quiz',
        ),
    ]
