# Generated by Django 5.1.4 on 2025-01-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_rename_fields_quizquestion_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '2. Специальность', 'verbose_name_plural': '2. Специальность'},
        ),
        migrations.AlterModelOptions(
            name='toplevelcategory',
            options={'verbose_name': '1. Тип образования', 'verbose_name_plural': '1. Тип образования'},
        ),
    ]
