# Generated by Django 5.1.4 on 2025-01-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0011_alter_quiz_options_uploadtests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadtests',
            options={'verbose_name': '4. Загрузить файл', 'verbose_name_plural': '4. Загрузить файл'},
        ),
        migrations.AddField(
            model_name='uploadtests',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_upload', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_option', to='quizz.quiz', verbose_name='Викторина'),
        ),
    ]
