# Generated by Django 5.1.4 on 2025-01-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0015_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderquiz',
            options={'verbose_name': '5. Заказать тест', 'verbose_name_plural': '5. Заказать тест'},
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст вопроса'),
        ),
    ]
