# Generated by Django 5.1.4 on 2025-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0016_alter_orderquiz_options_alter_questionoption_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('daytime', 'Очное'), ('evening', 'Вечернее'), ('remote', 'Дистанционное'), ('external', 'Экстернат')], max_length=10, null=True, verbose_name='Форма обучения'),
        ),
    ]
