# Generated by Django 5.1.4 on 2025-01-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0017_alter_quiz_mode_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('daytime', 'Kunduzki'), ('evening', 'Sirtqi'), ('remote', 'Masofaviy'), ('external', 'Tashqi')], max_length=10, null=True, verbose_name='Форма обучения'),
        ),
    ]
