# Generated by Django 5.1.4 on 2025-01-12 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0022_remove_usertestanswers_test_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswerquestion',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizz.questionoption'),
        ),
    ]
