# Generated by Django 5.1.4 on 2025-01-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0023_alter_testanswerquestion_selected_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAnswerQuestionOption',
        ),
    ]
