# Generated by Django 5.1.4 on 2025-01-16 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0024_delete_testanswerquestionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswerquestion',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_answer_questions', to='quizz.questionoption'),
        ),
    ]
