# Generated by Django 5.1.4 on 2025-01-16 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0025_alter_testanswerquestion_selected_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswerquestion',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_answer', to='quizz.questionoption'),
        ),
    ]
