# Generated by Django 5.1.4 on 2025-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0027_alter_testanswerquestion_test_answer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestanswers',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='usertestanswers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
    ]
