# Generated by Django 5.1.3 on 2025-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
