# Generated by Django 5.1.4 on 2025-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_last_issued',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
